kind: Job
apiVersion: batch/v1
metadata:
  name: nginx-job
  namespace: nginx
spec:
  completions: 1
  parallelism: 1 ## Number of pods to run in parallel on the job
  template:
    metadata:
      name: nginx-job-pod
      labels:
        app: batch-job
    spec:
      containers:
        - name: batch-container
          image: busybox:latest
          command: ["sh", "-c", "echo Hello, Kubernetes! && sleep 10"]
      restartPolicy: Never

